// Generated by CoffeeScript 1.7.1
(function() {
  var num, numbers, y, _i, _len;

  numbers = process.argv.slice(2);

  y = 0;

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    num = numbers[_i];
    y += Number(num);
  }

  console.log(y);

}).call(this);

//# sourceMappingURL=babysteps.map
