// Generated by CoffeeScript 1.7.1
(function() {
  var filtered_ls;

  filtered_ls = function(dir, ext, callback) {
    var fs;
    fs = require('fs');
    return fs.readdir(dir, function(err, files) {
      if (err) {
        return callback(err, null);
      } else {
        return callback(null, files.filter(function(x) {
          return x.match('\.' + ext + '$');
        }));
      }
    });
  };

  module.exports = filtered_ls;

}).call(this);

//# sourceMappingURL=filteredlsfunction.map
