// Generated by CoffeeScript 1.7.1
(function() {
  var m;

  m = require('./filteredlsfunction.js');

  m(process.argv[2], process.argv[3], function(err, files) {
    var file, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      _results.push(console.log(file));
    }
    return _results;
  });

}).call(this);

//# sourceMappingURL=modular.map
